
FROM lyft/envoy:latest

RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN apt-get update

WORKDIR /deployments

COPY target/boldmen-envoy-0.0.1-SNAPSHOT.jar .
COPY entrypoint-client.sh .

RUN chmod +x entrypoint-client.sh

ENTRYPOINT [ "./entrypoint-client.sh" ]